spring:
  mvc:
    static-path-pattern: /static/**
  datasource:
    #url: jdbc:h2:mem:h2test;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    url: jdbc:h2:./h2test;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    platform: h2
    username: sa
    password:
    driverClassName: org.h2.Driver
    continue-on-error: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true
  h2:
    console:
      enabled: true
      path: /console
      settings:
        trace: false
        web-allow-others: false
  influx:
     url: https://192.168.0.89:8086
     username: admin
     password: admin
logging:
  level: debug
server:
  port: 8080
security:
  basic:
    enabled: false
#  user:
#    name: admin
#    password: admin
#    roles: admin