CREATE TABLE t_user (
  id int NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  name varchar(255) DEFAULT NULL,
  password varchar(255) DEFAULT NULL,
  roles varchar(255) DEFAULT NULL,
  url varchar(255) DEFAULT NULL,
  PRIMARY KEY (id)
);

CREATE TABLE t_menu_item (
  id int NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  icon varchar(80) DEFAULT NULL,
  index varchar(80) NOT NULL,
  title varchar(80) NOT NULL,
  parent_id int DEFAULT 0,
  level int DEFAULT 0,
  PRIMARY KEY (id)
);